// ============================================================
// Tutorial Configuration - Guías paso a paso por módulo
// ============================================================

import { ModuleTutorial } from './types';

export const TUTORIAL_MODULES: ModuleTutorial[] = [
  // ── Dashboard ────────────────────────────────
  {
    moduleId: 'dashboard',
    moduleName: 'Dashboard Principal',
    description: 'Conoce tu panel de control y las métricas principales',
    category: 'Inicio',
    estimatedTime: 4,
    icon: 'LayoutDashboard',
    route: '/app',
    steps: [
      {
        id: 'dashboard-1',
        title: '👋 Bienvenido a tu Dashboard',
        description: 'Este es tu panel de control principal. Aquí verás un resumen de todas tus operaciones: ventas totales del mes, rentabilidad, cuentas por cobrar y saldo de clientes en tiempo real.',
        position: 'bottom',
        action: 'Observa los números en las tarjetas superiores',
      },
      {
        id: 'dashboard-2',
        target: '[data-tutorial="kpis"]',
        title: '📊 4 Indicadores Clave (KPIs)',
        description: 'Las 4 tarjetas principales muestran: (1) Ventas del Mes total, (2) Margen Bruto %, (3) Total Por Cobrar a clientes, (4) Saldo en cuentas de clientes. Cada tarjeta tiene un badge % que muestra cambio vs. mes anterior.',
        position: 'bottom',
        action: 'Haz clic en cualquier tarjeta para profundizar',
        duration: 5,
      },
      {
        id: 'dashboard-3',
        target: '[data-tutorial="chart-sales"]',
        title: '📈 Gráfico: Ventas de los Últimos 7 Días',
        description: 'Gráfico interactivo que muestra tendencia diaria de ventas. Eje X = Fecha, Eje Y = Monto en ARS. Es útil para identificar días picos y tendencias semanales. Pasa mouse sobre puntos para ver valores exactos.',
        position: 'top',
        action: 'Mueve el cursor sobre el gráfico para ver detalles',
        duration: 3,
      },
      {
        id: 'dashboard-4',
        title: '🚨 Alertas de Stock Bajo',
        description: 'En la parte inferior ves el panel de "Alertas de Stock Bajo". Aquí aparecen los productos que cayeron por debajo de su stock mínimo configurado. Cada alerta muestra: Nombre del producto, Stock mínimo requerido, Cantidad actual. Si ves alertas, es hora de reponer!',
        position: 'bottom',
        action: 'Revisa si hay productos que necesitan reposición urgente',
        duration: 3,
      },
    ],
  },

  // ── Ventas ────────────────────────────────
  {
    moduleId: 'sales',
    moduleName: 'Módulo de Ventas',
    description: 'Aprende a crear y gestionar tus ventas',
    category: 'Ventas',
    estimatedTime: 5,
    icon: 'ShoppingCart',
    route: '/sales',
    steps: [
      {
        id: 'sales-1',
        title: '🛒 Gestión de Ventas',
        description: 'En este módulo puedes ver todas tus ventas realizadas, crear nuevas ventas, y gestionar tus pedidos. Las ventas se crean desde POS (mostrador rápido) o desde este módulo para ventas más complejas.',
        position: 'bottom',
        action: 'Observa la interfaz principal',
      },
      {
        id: 'sales-2',
        title: '➕ Crear Nueva Venta',
        description: 'Haz clic en el botón "Nueva Venta" (arriba a la derecha). Se abrirá un formulario donde podrás: seleccionar cliente, agregar múltiples productos, elegir método de pago, aplicar descuentos y generar comprobante fiscal.',
        position: 'bottom',
        action: 'Busca el botón superior derecho',
        duration: 3,
      },
      {
        id: 'sales-3',
        target: '[data-tutorial="sales-table"]',
        title: '📋 Historial Completo de Ventas',
        description: 'Tabla con todas tus ventas: Número (correlativo AFIP), Fecha, Cliente, Productos listados, Método de pago (Efectivo/Tarjeta/Cheque), Total en ARS, Estado, y Acciones. Cada venta muestra un icono Receipt y se pueden ver detalles.',
        position: 'top',
        action: 'Haz clic en una venta para ver detalles completos o imprimir',
        duration: 3,
      },
      {
        id: 'sales-4',
        target: '[data-tutorial="sales-filters"]',
        title: '🔍 Búsqueda y Filtros',
        description: 'Usa la barra superior para filtrar: (1) Input "Buscar por número de venta" para encontrar por correlativo, (2) Select "Filtrar por producto" para ver qué ventas incluyen ese producto. Muy útil para reconciliaciones rápidas.',
        position: 'bottom',
        action: 'Prueba buscar una venta reciente',
        duration: 2,
      },
    ],
  },

  // ── Productos ────────────────────────────────
  {
    moduleId: 'products',
    moduleName: 'Gestión de Productos',
    description: 'Administra tu catálogo de productos e inventario',
    category: 'Inventario',
    estimatedTime: 5,
    icon: 'Package',
    route: '/products',
    steps: [
      {
        id: 'products-1',
        title: '📦 Tu Catálogo de Productos',
        description: 'Aquí ves todas tus productos activos. El catálogo incluye: Código SKU único, Código de barras, Nombre, Precio de venta, Stock actual, Proveedor, Categoría. Los productos aparecen en orden de creación o filtrados.',
        position: 'bottom',
        action: 'Observa la lista de productos disponibles',
      },
      {
        id: 'products-2',
        target: '[data-tutorial="btn-create-product"]',
        title: '➕ Agregar Nuevo Producto',
        description: 'Haz clic en el botón "Nuevo Producto" (arriba derecha). Se abre formulario donde defines: Nombre, SKU, Código de barras (para POS), Precio de costo, Precio de venta, Stock inicial, Categoría, Impuesto (IVA 21%, 10.5% o 0%), Proveedor preferido, Imagen.',
        position: 'bottom',
        action: 'Crea tu primer producto',
        duration: 4,
      },
      {
        id: 'products-3',
        target: '[data-tutorial="product-table"]',
        title: '📊 Información del Producto',
        description: 'Cada fila muestra: icono Receipt, Código, Nombre, Precio, Stock actual (en verde si OK, en rojo si bajo), Margen %, Proveedor. Haz clic en producto para editar o ver historial de ventas.',
        position: 'top',
        action: 'Selecciona un producto para ver detalles',
        duration: 2,
      },
      {
        id: 'products-4',
        title: '⚠️ Alertas Automáticas de Stock Bajo',
        description: 'Configura stock mínimo para cada producto. Cuando alcance ese nivel, se dispara alerta automática (aparece en Dashboard). Ejemplo: si mínimo es 5 y llega a 4, se alerta. Así no se te agota stock sin que lo sepas.',
        position: 'left',
        action: 'Configura stock mínimo de 2-3 productos de prueba',
        duration: 2,
      },
    ],
  },

  // ── Clientes ────────────────────────────────
  {
    moduleId: 'customers',
    moduleName: 'Base de Clientes',
    description: 'Administra y conoce mejor a tus clientes',
    category: 'Clientes',
    estimatedTime: 4,
    icon: 'Users',
    route: '/customers',
    steps: [
      {
        id: 'customers-1',
        title: '👥 Base de Clientes Completa',
        description: 'Registro centralizado de todos tus clientes: Nombre, Teléfono, Email, Dirección, CUIT/DNI, Límite de crédito, Saldo pendiente, Última compra, Total gasto histórico. Es la fuente de verdad para gestionar relaciones.',
        position: 'bottom',
        action: 'Observa la lista de clientes registrados',
      },
      {
        id: 'customers-2',
        title: '➕ Agregar Nuevo Cliente',
        description: 'Haz clic en "Nuevo Cliente" (arriba derecha). Completa: Nombre completo, Teléfono, Email (para enviar cotizaciones/facturas), Dirección completa, CUIT/DNI, Límite de crédito para venta a crédito, se sugiere categorizar (mayorista, minorista, consumidor).',
        position: 'bottom',
        action: 'Agrega 2-3 clientes de prueba',
        duration: 3,
      },
      {
        id: 'customers-3',
        title: '🎯 Perfil del Cliente',
        description: 'Haz clic en cliente para ver: resumen completo, todas sus compras (historial), movimientos de cuenta corriente, deuda acumulada, descuentos aplicados, datos para contacto. Lugar central para todo sobre ese cliente.',
        position: 'right',
        action: 'Abre perfil de un cliente existente',
        duration: 2,
      },
      {
        id: 'customers-4',
        title: '🔍 Búsqueda Rápida',
        description: 'La barra de búsqueda superior busca por: nombre del cliente, teléfono, email, CUIT/DNI. Escribe parcial y te autocompleta. Muy útil para encontrar rápido durante una venta al teléfono.',
        position: 'bottom',
        action: 'Prueba buscar un cliente reciente',
        duration: 2,
      },
    ],
  },

  // ── Inventario ────────────────────────────────
  {
    moduleId: 'inventory',
    moduleName: 'Control de Inventario',
    description: 'Monitorea stock y recibe alertas automáticas',
    category: 'Inventario',
    estimatedTime: 4,
    icon: 'Warehouse',
    route: '/inventory-alerts',
    steps: [
      {
        id: 'inventory-1',
        title: '📦 Centro de Control de Stock',
        description: 'Vista centralizada de QUÉ productos tienen bajo stock. El sistema monitorea automáticamente todos tus productos contra su nivel mínimo configurado. Es tu early warning system para evitar desabastecimiento.',
        position: 'bottom',
        action: 'Observa qué productos tienen alertas activas',
      },
      {
        id: 'inventory-2',
        title: '🚨 Panel de Alertas Críticas',
        description: 'Los productos que aparecen aquí están por debajo del mínimo establecido. Colores: Verde (OK), Naranja (Próximo a mínimo), Rojo (Crítico, reponer urgente). Cada alerta muestra el gap: cuánto falta para llegar a mínimo.',
        position: 'bottom',
        action: 'Identifica los 2-3 productos más críticos',
        duration: 3,
      },
      {
        id: 'inventory-3',
        title: '📊 Tabla Completa de Stock',
        description: 'Ves todos tus productos con: Nombre, Código, Stock Actual, Stock Mínimo configurado, Diferencia, Última compra fecha, Rotación (veces/mes que se vende). Te permite priorizar qué reponer primero.',
        position: 'top',
        action: 'Revisa los niveles por producto',
        duration: 2,
      },
      {
        id: 'inventory-4',
        title: '📝 Crear Orden de Recompra Automática',
        description: 'Selecciona productos de la lista y haz clic "Crear Orden". Se genera automáticamente una orden de compra pre-cargada con cantidad sugerida (para llegar a mínimo + 1 mes de venta promedio).',
        position: 'left',
        action: 'Prueba crear una orden por productos bajos',
        duration: 2,
      },
    ],
  },

  // ── Punto de Venta (POS) ────────────────────────────────
  {
    moduleId: 'pos',
    moduleName: 'Punto de Venta (POS)',
    description: 'Gestiona ventas rápidas y directas en caja',
    category: 'General',
    estimatedTime: 6,
    icon: 'ShoppingCart',
    route: '/pos',
    steps: [
      {
        id: 'pos-1',
        title: '🛒 Terminal de Punto de Venta (POS)',
        description: 'Este es tu caja rápida. Aquí capturarás ventas del mostrador en segundos: busca producto, agrega cantidad, selecciona método de pago, confirma. El flujo está optimizado para velocidad. Se genera automáticamente recibo o factura fiscal.',
        position: 'bottom',
        action: 'Observa la pantalla completa de la caja',
      },
      {
        id: 'pos-2',
        title: '🔍 Búsqueda de Productos',
        description: 'Campo de entrada en la izquierda superior. Puedes: (1) Escribir nombre del producto (ej: "Leche"), (2) Escanear código de barras directamente (si tienes lector), (3) Escribir SKU del producto. Autocompleta mientras escribes.',
        position: 'bottom',
        action: 'Busca y agrega 1-2 productos',
        duration: 3,
      },
      {
        id: 'pos-3',
        title: '🛍️ Carrito de Compra (Derecha)',
        description: 'Lado derecho muestraItems agregados. Cada línea: Nombre, Precio unitario, Cantidad (controles + -), Subtotal. Botones: Editar cantidad, Eliminar (🗑). En rojo alertas si no hay stock. Scroll si hay muchos items.',
        position: 'left',
        action: 'Agrega varios productos y prueba cambiar cantidades',
        duration: 2,
      },
      {
        id: 'pos-4',
        title: '💳 Método de Pago',
        description: 'Selector debajo del carrito. Opciones: Efectivo (sin recargo), Tarjeta débito (sin recargo), Tarjeta crédito (con opciones de cuotas 3/6/12, cada una con su recargo %), Cheque (a fecha), Transferencia. Selecciona según cliente.',
        position: 'top',
        action: 'Prueba diferentes métodos de pago',
        duration: 2,
      },
      {
        id: 'pos-5',
        title: '✅ Resumen y Finalizar Venta',
        description: 'En botones finales: Total en ARS grande, Descuentos aplicables, Botón "Cobrar" verde. Al clickear: verifica pago (efectivo, tarjeta, etc.), genera comprobante AFIP automático, actualiza stock, guarda venta. Se muestra recibo para imprimir.',
        position: 'top',
        action: 'Completa la venta hasta el final',
        duration: 3,
      },
    ],
  },

  // ── Presupuestos ────────────────────────────────
  {
    moduleId: 'quotations',
    moduleName: 'Presupuestos',
    description: 'Crea presupuestos para tus clientes',
    category: 'Ventas',
    estimatedTime: 4,
    icon: 'FileCheck',
    route: '/quotations',
    steps: [
      {
        id: 'quotations-1',
        title: '📋 Gestión de Presupuestos',
        description: 'Crea cotizaciones detalladas para tus clientes antes de cerrar ventas. Presupuestos incluyen: Cliente, Productos con precios, Descuentos, Validez (días hasta vencimiento), Notas comerciales, Total final.',
        position: 'bottom',
        action: 'Observa presupuestos existentes o historial',
      },
      {
        id: 'quotations-2',
        title: '➕ Crear Nuevo Presupuesto',
        description: 'Botón "Nuevo Presupuesto" arriba. Selecciona cliente, agrega productos misma interfaz que POS, establece días de validez (ej: 7, 15, 30 días), agrega notas especiales si aplica (volumen, términos de pago especiales).',
        position: 'bottom',
        action: 'Crea un presupuesto de prueba',
        duration: 3,
      },
      {
        id: 'quotations-3',
        title: '📊 Historial y Estados',
        description: 'Tabla con: Número presupuesto, Fecha creación, Cliente, Total, Estado (Pendiente = esperando respuesta cliente, Aceptado, Rechazado, Vencido). Cada presupuesto tiene fecha autocalculada de vencimiento.',
        position: 'top',
        action: 'Haz clic en uno para ver detalles',
      },
      {
        id: 'quotations-4',
        title: '📄 Enviar y Exportar a PDF',
        description: 'Cada presupuesto puede: Enviarse por mail directamente al cliente (con email precompletado), Descargarse en PDF profesional (con logo empresa), Convertirse en venta confirma (si cliente acepta).',
        position: 'left',
        action: 'Exporta un presupuesto a PDF',
      },
    ],
  },

  // ── Remitos/Notas de Entrega ────────────────────────────────
  {
    moduleId: 'delivery_notes',
    moduleName: 'Remitos/Notas de Entrega',
    description: 'Gestiona entregas de productos',
    category: 'Ventas',
    estimatedTime: 4,
    icon: 'Truck',
    route: '/delivery-notes',
    steps: [
      {
        id: 'delivery-1',
        title: '🚚 Remitos de Entrega',
        description: 'Registra las entregas de productos a tus clientes.',
        position: 'bottom',
        action: 'Observa los remitos pendientes',
      },
      {
        id: 'delivery-2',
        target: '[data-tutorial="btn-create-delivery"]',
        title: '➕ Crear Remito',
        description: 'Haz clic para crear un nuevo remito de entrega.',
        position: 'bottom',
        action: 'Inicia un remito',
        duration: 3,
      },
      {
        id: 'delivery-3',
        target: '[data-tutorial="delivery-table"]',
        title: '📋 Historial de Entregas',
        description: 'Todas tus entregas registradas con fecha, cliente y estado.',
        position: 'top',
        action: 'Haz clic para ver detalles',
      },
      {
        id: 'delivery-4',
        target: '[data-tutorial="track-delivery"]',
        title: '📍 Rastreo de Entregas',
        description: 'Actualiza el estado: pendiente, en camino, entregado, devuelto.',
        position: 'left',
        action: 'Actualiza el estado de una entrega',
      },
    ],
  },

  // ── Devoluciones de Venta ────────────────────────────────
  {
    moduleId: 'returns',
    moduleName: 'Devoluciones de Venta',
    description: 'Gestiona devoluciones de clientes',
    category: 'Ventas',
    estimatedTime: 4,
    icon: 'TrendingDown',
    route: '/returns',
    steps: [
      {
        id: 'returns-1',
        title: '📉 Gestión de Devoluciones',
        description: 'Registra devoluciones de productos que los clientes devuelven.',
        position: 'bottom',
        action: 'Observa las devoluciones registradas',
      },
      {
        id: 'returns-2',
        target: '[data-tutorial="btn-create-return"]',
        title: '➕ Nueva Devolución',
        description: 'Haz clic para crear una devolución. Selecciona la venta original y los productos.',
        position: 'bottom',
        action: 'Inicia una nueva devolución',
        duration: 3,
      },
      {
        id: 'returns-3',
        target: '[data-tutorial="return-reason"]',
        title: '❓ Motivo de Devolución',
        description: 'Especifica por qué el cliente devuelve: producto defectuoso, cambio, no quiere, etc.',
        position: 'top',
        action: 'Selecciona el motivo',
      },
      {
        id: 'returns-4',
        target: '[data-tutorial="process-return"]',
        title: '✅ Procesar Devolución',
        description: 'Registra la devolución y genera el documento. El stock se actualiza automáticamente.',
        position: 'top',
        action: 'Completa el proceso',
      },
    ],
  },

  // ── Reservas de Productos ────────────────────────────────
  {
    moduleId: 'reservations',
    moduleName: 'Reservas de Productos',
    description: 'Reserva productos para clientes',
    category: 'Ventas',
    estimatedTime: 3,
    icon: 'Calendar',
    route: '/reservations',
    steps: [
      {
        id: 'reservations-1',
        title: '📅 Sistema de Reservas',
        description: 'Reserva productos para clientes que los comprarán en el futuro.',
        position: 'bottom',
        action: 'Observa las reservas activas',
      },
      {
        id: 'reservations-2',
        target: '[data-tutorial="btn-reserve"]',
        title: '➕ Crear Reserva',
        description: 'Selecciona cliente, productos y fecha de retiro.',
        position: 'bottom',
        action: 'Crea una nueva reserva',
        duration: 3,
      },
      {
        id: 'reservations-3',
        target: '[data-tutorial="reservation-status"]',
        title: '⏳ Estados de Reserva',
        description: 'Pendiente: esperando al cliente. Retirada: el cliente la recibió.',
        position: 'top',
        action: 'Cambia el estado según corresponda',
      },
      {
        id: 'reservations-4',
        target: '[data-tutorial="expiry-date"]',
        title: '⏰ Vencimiento de Reserva',
        description: 'Las reservas expiran si no se retiran a tiempo. Configura el período de validez.',
        position: 'left',
        action: 'Observa las fechas de vencimiento',
      },
    ],
  },

  // ── Cuentas Corrientes ────────────────────────────────
  {
    moduleId: 'accounts_receivable',
    moduleName: 'Cuentas Corrientes',
    description: 'Gestiona deudas y pagos de clientes',
    category: 'Clientes',
    estimatedTime: 4,
    icon: 'Receipt',
    route: '/accounts-receivable',
    steps: [
      {
        id: 'accrec-1',
        title: '🧾 Cuentas Corrientes de Clientes',
        description: 'Aquí ves el estado de cada cliente: cuánto debe, cuándo vence, y su historial de pagos.',
        position: 'bottom',
        action: 'Observa los saldos pendientes',
      },
      {
        id: 'accrec-2',
        target: '[data-tutorial="customer-debt"]',
        title: '💰 Saldo Pendiente',
        description: 'En rojo aparecen clientes con saldo vencido. En naranja, próximos a vencer.',
        position: 'bottom',
        action: 'Identifica clientes que deben',
        duration: 3,
      },
      {
        id: 'accrec-3',
        target: '[data-tutorial="payment-record"]',
        title: '📝 Registrar Pago',
        description: 'Haz clic para registrar un pago recibido de un cliente.',
        position: 'top',
        action: 'Registra un pago',
      },
      {
        id: 'accrec-4',
        target: '[data-tutorial="payment-history"]',
        title: '📊 Historial de Pagos',
        description: 'Ve todas las transacciones del cliente: fechas, montos y fechas de pago.',
        position: 'left',
        action: 'Consulta el historial',
      },
    ],
  },

  // ── Atención al Cliente ────────────────────────────────
  {
    moduleId: 'customer_support',
    moduleName: 'Atención al Cliente',
    description: 'Gestiona tickets de soporte y consultas',
    category: 'Clientes',
    estimatedTime: 5,
    icon: 'MessageCircle',
    steps: [
      {
        id: 'support-1',
        title: '💬 Centro de Soporte al Cliente',
        description: 'Registro de tickets, consultas y reclamos de clientes.',
        position: 'bottom',
        action: 'Observa los tickets abiertos',
      },
      {
        id: 'support-2',
        target: '[data-tutorial="btn-new-ticket"]',
        title: '➕ Crear Ticket',
        description: 'Abre un nuevo ticket para registrar una consulta o reclamo de cliente.',
        position: 'bottom',
        action: 'Inicia un ticket',
        duration: 3,
      },
      {
        id: 'support-3',
        target: '[data-tutorial="ticket-priority"]',
        title: '🚨 Nivel de Prioridad',
        description: 'Baja, Media, Alta o Urgente. Ordena las tareas por importancia.',
        position: 'top',
        action: 'Asigna una prioridad',
      },
      {
        id: 'support-4',
        target: '[data-tutorial="ticket-resolution"]',
        title: '✅ Resolver Ticket',
        description: 'Cierra el ticket cuando el problema se haya solucionado.',
        position: 'top',
        action: 'Resuelve un ticket',
      },
      {
        id: 'support-5',
        target: '[data-tutorial="customer-satisfaction"]',
        title: '⭐ Calificación del Cliente',
        description: 'Los clientes califican la resolución de su problema (1-5 estrellas).',
        position: 'left',
        action: 'Observa las calificaciones',
      },
    ],
  },

  // ── Órdenes de Compra ────────────────────────────────
  {
    moduleId: 'purchase_orders',
    moduleName: 'Órdenes de Compra',
    description: 'Crea y gestiona órdenes a proveedores',
    category: 'Compras',
    estimatedTime: 4,
    icon: 'FileCheck',
    route: '/purchase-orders',
    steps: [
      {
        id: 'po-1',
        title: '✅ Órdenes de Compra',
        description: 'Cria órdenes formales para solicitar productos a tus proveedores. Cada orden incluye: Proveedor, Productos, Cantidades, Precios, Descuentos, Total, Período de entrega estimado.',
        position: 'bottom',
        action: 'Observa órdenes pendientes o historial',
      },
      {
        id: 'po-2',
        title: '➕ Nueva Orden de Compra',
        description: 'Botón "Nueva Orden" arriba. Selecciona proveedor (precarga precios especiales negociados), agrega productos con cantidades, especifica fecha entrega requerida, añade notas adicionales, genera PDF para enviar.',
        position: 'bottom',
        action: 'Crea una orden de compra',
        duration: 3,
      },
      {
        id: 'po-3',
        title: '🔄 Ciclo de Vida de la Orden',
        description: 'Estados automáticos: Borrador (editandose), Enviada (a proveedor), Confirmada (proveedor acepta), Parcialmente recibida (llegan algunos items), Completamente recibida, Cancelada. Cada transición actualiza estados en recepción.',
        position: 'top',
        action: 'Monitorea el estado de tus órdenes',
      },
      {
        id: 'po-4',
        title: '✓ Recepción de Mercadería Vinculada',
        description: 'Cuando llega en Modulo "Recepción" selecciona la orden PO, confirma items recibidos, valida cantidades y calidad. Stock se actualiza automáticamente en Productos.',
        position: 'left',
        action: 'Vincula a recepción cuando llegue',
      },
    ],
  },

  // ── Compras ────────────────────────────────
  {
    moduleId: 'purchases',
    moduleName: 'Historial de Compras',
    description: 'Historial completo de todas tus compras',
    category: 'Compras',
    estimatedTime: 3,
    icon: 'ShoppingBag',
    route: '/purchases',
    steps: [
      {
        id: 'purchases-1',
        title: '🛍️ Historial de Compras',
        description: 'Registro de todas las compras realizadas a proveedores.',
        position: 'bottom',
        action: 'Observa el historial de compras',
      },
      {
        id: 'purchases-2',
        target: '[data-tutorial="purchases-filters"]',
        title: '🔍 Filtrar por Período',
        description: 'Busca compras por fecha, proveedor o estado de pago.',
        position: 'bottom',
        action: 'Filtra por lo que necesites',
        duration: 3,
      },
      {
        id: 'purchases-3',
        target: '[data-tutorial="purchase-detail"]',
        title: '📋 Detalle de Compra',
        description: 'Haz clic en una compra para ver: productos, cantidades, precios e impuestos.',
        position: 'top',
        action: 'Revisa una compra completa',
      },
      {
        id: 'purchases-4',
        target: '[data-tutorial="invoice-attachment"]',
        title: '📎 Adjuntar Factura',
        description: 'Sube la factura del proveedor para tener registro completo.',
        position: 'left',
        action: 'Adjunta documentos',
      },
    ],
  },

  // ── Recepción de Mercadería ────────────────────────────────
  {
    moduleId: 'purchase_reception',
    moduleName: 'Recepción de Mercadería',
    description: 'Registra la llegada de productos del proveedor',
    category: 'Compras',
    estimatedTime: 3,
    icon: 'PackageCheck',
    route: '/purchase-reception',
    steps: [
      {
        id: 'reception-1',
        title: '✓ Recepción de Mercadería',
        description: 'Registra cuando reciben productos del proveedor. El stock se actualiza automáticamente.',
        position: 'bottom',
        action: 'Observa recepciones pendientes',
      },
      {
        id: 'reception-2',
        target: '[data-tutorial="receive-order"]',
        title: '📦 Recibir Orden',
        description: 'Selecciona la orden de compra y confirma la cantidad recibida.',
        position: 'bottom',
        action: 'Confirma una recepción',
        duration: 3,
      },
      {
        id: 'reception-3',
        target: '[data-tutorial="check-items"]',
        title: '✔️ Verificar Items',
        description: 'Comprueba que has recibido la cantidad correcta de cada producto.',
        position: 'top',
        action: 'Valida los artículos',
      },
      {
        id: 'reception-4',
        target: '[data-tutorial="quality-check"]',
        title: '🔍 Control de Calidad',
        description: 'Registra si hay dañados, vencidos o defectuosos antes de aceptar.',
        position: 'left',
        action: 'Marca problemas si los hay',
      },
    ],
  },

  // ── Devoluciones a Proveedores ────────────────────────────────
  {
    moduleId: 'purchase_returns',
    moduleName: 'Devoluciones a Proveedores',
    description: 'Gestiona devoluciones de productos al proveedor',
    category: 'Compras',
    estimatedTime: 3,
    icon: 'TrendingDown',
    route: '/purchase-returns',
    steps: [
      {
        id: 'pret-1',
        title: '📉 Devoluciones a Proveedores',
        description: 'Registra cuando devuelves productos dañados o no conformes al proveedor.',
        position: 'bottom',
        action: 'Observa devoluciones registradas',
      },
      {
        id: 'pret-2',
        target: '[data-tutorial="btn-create-return"]',
        title: '➕ Nueva Devolución',
        description: 'Selecciona la compra original y los productos a devolver.',
        position: 'bottom',
        action: 'Inicia una devolución',
        duration: 3,
      },
      {
        id: 'pret-3',
        target: '[data-tutorial="return-reason"]',
        title: '❓ Motivo de Devolución',
        description: 'Especifica: Defectuoso, Vencido, No conforme a especificación, Cantidad sobrante.',
        position: 'top',
        action: 'Selecciona el motivo',
      },
      {
        id: 'pret-4',
        target: '[data-tutorial="refund-status"]',
        title: '💰 Estado del Reembolso',
        description: 'Registra si ya recibiste crédito, nota de débito o efectivo del proveedor.',
        position: 'left',
        action: 'Actualiza estado',
      },
    ],
  },

  // ── Proveedores ────────────────────────────────
  {
    moduleId: 'suppliers',
    moduleName: 'Base de Proveedores',
    description: 'Administra tu cartera de proveedores',
    category: 'Compras',
    estimatedTime: 3,
    icon: 'Truck',
    route: '/suppliers',
    steps: [
      {
        id: 'suppliers-1',
        title: '🚚 Base de Proveedores',
        description: 'Registro de todos tus proveedores: datos de contacto, condiciones de pago y términos.',
        position: 'bottom',
        action: 'Observa la lista de proveedores',
      },
      {
        id: 'suppliers-2',
        target: '[data-tutorial="btn-add-supplier"]',
        title: '➕ Agregar Proveedor',
        description: 'Crea nuevo proveedor con: nombre, CUIT, contacto, dirección y condiciones de pago.',
        position: 'bottom',
        action: 'Agrega un proveedor',
        duration: 3,
      },
      {
        id: 'suppliers-3',
        target: '[data-tutorial="supplier-terms"]',
        title: '📋 Condiciones Comerciales',
        description: 'Plazo de pago, descuentos por volumen, mínimo de compra, formas de pago aceptadas.',
        position: 'top',
        action: 'Revisa los términos',
      },
      {
        id: 'suppliers-4',
        target: '[data-tutorial="supplier-rating"]',
        title: '⭐ Calificación del Proveedor',
        description: 'Registra evaluaciones: calidad, puntualidad en entregas, precio competitivo.',
        position: 'left',
        action: 'Califica un proveedor',
      },
    ],
  },

  // ── Cuentas Bancarias ────────────────────────────────
  {
    moduleId: 'bank_accounts',
    moduleName: 'Cuentas Bancarias',
    description: 'Gestiona tus cuentas bancarias',
    category: 'Finanzas',
    estimatedTime: 3,
    icon: 'Building2',
    route: '/bank-accounts',
    steps: [
      {
        id: 'bank-1',
        title: '🏦 Registro de Cuentas Bancarias',
        description: 'Panel centralizado de todas tus cuentas: Banco, Tipo (Corriente/Caja Ahorro), Número cuenta, Titularidad, Saldo actual, Límite disponible, Moneda (ARS/USD).',
        position: 'bottom',
        action: 'Observa tus cuentas activas',
      },
      {
        id: 'bank-2',
        title: '➕ Agregar Nueva Cuenta',
        description: 'Botón Agregar. Especifica: Banco (dropdown), Sucursal, Número cuenta, Alias para transferencias, Titularidad (nombre legal), Moneda, Saldo inicial (para registros históricos).',
        position: 'bottom',
        action: 'Agrega tu matriz principal y caja de ahorro',
        duration: 3,
      },
      {
        id: 'bank-3',
        title: '💰 Saldo en Tiempo Real',
        description: 'Cada cuenta muestra saldo actualizado con todos los movimientos registrados. Es la fuente de verdad. Puedes reconciliar vs. extracto bancario en módulo "Movimientos Bancarios".',
        position: 'top',
        action: 'Verifica los saldos',
      },
      {
        id: 'bank-4',
        title: '🔗 Vinculación de Movimientos',
        description: 'Cuando registras movimientos (depósitos, transferencias), los asocias a esta cuenta. Sistema las agrupa por cuenta para reportes contables.',
        position: 'left',
        action: 'Referencia para módulo de movimientos',
      },
    ],
  },

  // ── Movimientos Bancarios ────────────────────────────────
  {
    moduleId: 'bank_movements',
    moduleName: 'Movimientos Bancarios',
    description: 'Registra transacciones bancarias',
    category: 'Finanzas',
    estimatedTime: 3,
    icon: 'TrendingUp',
    route: '/bank-movements',
    steps: [
      {
        id: 'bankm-1',
        title: '📈 Historial de Movimientos Bancarios',
        description: 'Registra TODOS los movimientos: Depósitos (dinero que entra), Extracciones (dinero que sale), Transferencias entre cuentas propias, Comisiones cobradas. Esencial para reconciliación contable.',
        position: 'bottom',
        action: 'Observa movimientos del mes',
      },
      {
        id: 'bankm-2',
        title: '➕ Registrar Nuevo Movimiento',
        description: 'Botón Nuevo. Especifica: Tipo (Depósito/Extracción/Transferencia), Cuenta origen, Cuenta destino (si aplica), Monto, Fecha, Concepto (ej: "Venta POS 25/3", "Pago nómina bancario"). Se vincula automáticamente a venta si aplica.',
        position: 'bottom',
        action: 'Registra 2-3 movimientos de prueba',
        duration: 3,
      },
      {
        id: 'bankm-3',
        title: '🔀 Categorización de Movimientos',
        description: 'Cada movimiento es: Entrada (aumenta saldo), Salida (disminuye), Transferencia (de una cuenta a otra). Se agrupa automáticamente en reportes por tipo para análisis de flujo de caja.',
        position: 'top',
        action: 'Entiende el flujo de tu caja',
      },
      {
        id: 'bankm-4',
        title: '✔️ Conciliación Bancaria',
        description: 'Compara tus registros con extracto del banco. Descarga movimientos del banco, márcalos como "Conciliados". Sistema alerta si hay discrepancias (movimiento sistema no coincide con banco).',
        position: 'left',
        action: 'Punto crítico de control',
      },
    ],
  },

  // ── Movimientos de Tarjetas ────────────────────────────────
  {
    moduleId: 'card_movements',
    moduleName: 'Movimientos de Tarjetas',
    description: 'Gestiona transacciones de tarjetas de crédito/débito',
    category: 'Finanzas',
    estimatedTime: 3,
    icon: 'CreditCard',
    route: '/card-movements',
    steps: [
      {
        id: 'card-1',
        title: '💳 Movimientos de Tarjetas',
        description: 'Registro de transacciones con tarjetas de crédito/débito: (1) Compras a surtidor, (2) Pagos de cuotas previas, (3) Adelantos de dinero, (4) Cargos de membresía. Esencial para reconciliación con extractos.',
        position: 'bottom',
        action: 'Observa transacciones del mes',
      },
      {
        id: 'card-2',
        title: '➕ Registrar Transacción',
        description: 'Botón Nuevo. Especifica: Tarjeta usada (dropdown), Tipo compra (Comercial/Adelanto/Pago), Monto, Fecha, Comercio/Concepto, Si es cuota: cuota X de Y. Sistema calcula automáticamente próximo vencimiento.',
        position: 'bottom',
        action: 'Registra una compra de prueba',
        duration: 3,
      },
      {
        id: 'card-3',
        title: '🎫 Gestión de Tarjetas',
        description: 'Cada tarjeta tu empresa usa: Tipo (Crédito/Débito), Banco emisor, Titular, Últimos 4 dígitos, Límite disponible, Vencimiento. Datos para control de gastos vs. presupuesto.',
        position: 'top',
        action: 'Revisa todas tus tarjetas activas',
      },
      {
        id: 'card-4',
        title: '📊 Resumen y Reportes',
        description: 'Genera resumen por tarjeta/período: Total gasto, Transacciones pendientes, Próximo vencimiento de pago, Saldo rotativo. Exporta para contador/fiscalista.',
        position: 'left',
        action: 'Genera reporte del mes',
      },
    ],
  },

  // ── Retenciones Fiscales ────────────────────────────────
  {
    moduleId: 'retentions',
    moduleName: 'Retenciones Fiscales',
    description: 'Gestiona retenciones de impuestos',
    category: 'Finanzas',
    estimatedTime: 3,
    icon: 'Calculator',
    route: '/retentions',
    steps: [
      {
        id: 'retention-1',
        title: '🧮 Registro de Retenciones Fiscales',
        description: 'Cuando proveedores te retienen dinero por impuestos (Ganancias, IVA) o cuando tu empresa retiene a otros. Essential para: (1) Crédito fiscal, (2) Acudir ante AFIP, (3) Reconciliación de pagos.',
        position: 'bottom',
        action: 'Observa retenciones acumuladas',
      },
      {
        id: 'retention-2',
        title: '➕ Registrar Nueva Retención',
        description: 'Botón Nuevo. Especifica: Tipo retención (Ganancias 35%/21%, IVA 9%/6%, Bienes Personales 1.25%), Período fiscal, Monto retenido, Número de comprobante, Proveedor/Empresa que retiene, Notas. Sistema guarda para acreditar.',
        position: 'bottom',
        action: 'Registra una retención de prueba',
        duration: 3,
      },
      {
        id: 'retention-3',
        title: '📋 Clasificación por Tipo',
        description: 'Sistema clasifica retenciones por tipo: Impuesto a Ganancias (para acreitar en declaración jurada), IVA (para crédito fiscal), Bienes Personales. Cada categoría agrupa para reporte mensual/anual.',
        position: 'top',
        action: 'Entiende cada tipo de retención',
      },
      {
        id: 'retention-4',
        title: '📊 Resumen para Contador',
        description: 'Genera reporte de retenciones pagadas/soportadas por período. Exporta detalle para que contador lo use en declaración jurada y acreditación de impuestos ante AFIP.',
        position: 'left',
        action: 'Exporta resumen del trimestre',
      },
    ],
  },

  // ── Servicios Técnicos ────────────────────────────────
  {
    moduleId: 'technical_services',
    moduleName: 'Servicios Técnicos',
    description: 'Gestiona servicios técnicos y reparaciones',
    category: 'Operaciones',
    estimatedTime: 4,
    icon: 'Wrench',
    route: '/technical-services',
    steps: [
      {
        id: 'tech-1',
        title: '🔧 Servicios Técnicos',
        description: 'Registro de trabajos técnicos, reparaciones y mantenimientos.',
        position: 'bottom',
        action: 'Observa los servicios pendientes',
      },
      {
        id: 'tech-2',
        target: '[data-tutorial="new-service"]',
        title: '➕ Crear Trabajo',
        description: 'Selecciona cliente, describe el problema, asigna técnico y prioridad.',
        position: 'bottom',
        action: 'Inicia un nuevo trabajo',
        duration: 3,
      },
      {
        id: 'tech-3',
        target: '[data-tutorial="service-status"]',
        title: '⏳ Estados del Servicio',
        description: 'Nuevo, En progreso, En espera de partes, Completado, Cancelado.',
        position: 'top',
        action: 'Actualiza el estado',
      },
      {
        id: 'tech-4',
        target: '[data-tutorial="service-invoice"]',
        title: '📄 Generar Factura',
        description: 'Una vez completado, genera factura con mano de obra y partes utilizadas.',
        position: 'left',
        action: 'Crea la factura',
      },
    ],
  },

  // ── Caja/Caja Chica ────────────────────────────────
  {
    moduleId: 'cash_register',
    moduleName: 'Gestión de Caja',
    description: 'Control de caja diaria',
    category: 'Operaciones',
    estimatedTime: 4,
    icon: 'DollarSign',
    route: '/cash-register',
    steps: [
      {
        id: 'cash-1',
        title: '💵 Control de Caja',
        description: 'Gestión del dinero físico en mostrador. Tracking: Apertura (dinero inicial), Entradas (ventas), Salidas (gastos/cambios), Cierre (recuento y depósito). Previene faltantes y fraudes.',
        position: 'bottom',
        action: 'Observa estado de caja del día',
      },
      {
        id: 'cash-2',
        title: '📖 Apertura de Caja',
        description: 'Inicio del día: especifica monto inicial en caja (ej: $1.000 en billetes/monedas), reembolso anterior, etc. Debe hacerse ANTES de vendedores. Sistema registra usuario, hora, fecha.',
        position: 'bottom',
        action: 'Abre caja de hoy',
        duration: 2,
      },
      {
        id: 'cash-3',
        title: '➕➖ Movimientos Diarios',
        description: 'El sistema registra automáticamente: Ventas POS (entran), Devoluciones (salen), Gastos (gasolina, papelería, etc - salen). Puedes agregar movimientos manuales (reembolsos empleados, adelantos).',
        position: 'top',
        action: 'Revisa los movimientos del día',
        duration: 2,
      },
      {
        id: 'cash-4',
        title: '🔒 Cierre de Caja',
        description: 'Fin de día: Cuenta dinero físico, ingresa total, sistema calcula faltante/sobrante vs. saldo teórico. Si cuadra exacto, genera comprobante cierre. Dinero se deposita en banco al día siguiente.',
        position: 'left',
        action: 'Cierra caja correctamente',
        duration: 2,
      },
    ],
  },

  // ── Gastos ────────────────────────────────
  {
    moduleId: 'expenses',
    moduleName: 'Gestión de Gastos',
    description: 'Registra gastos operativos de tu negocio',
    category: 'Operaciones',
    estimatedTime: 3,
    icon: 'Receipt',
    route: '/expenses',
    steps: [
      {
        id: 'expenses-1',
        title: '🧾 Registro de Gastos Operativos',
        description: 'Controla TODO dinero que sale: Servicios (electricidad, internet, teléfono), Suministros (papel, tinta), Mantenimiento (reparaciones), Publicidad, Viajes/combustible, Otros. Base para análisis de costos y rentabilidad.',
        position: 'bottom',
        action: 'Observa gastos del mes',
      },
      {
        id: 'expenses-2',
        title: '➕ Registrar Nuevo Gasto',
        description: 'Botón Nuevo. Especifica: Descripción (ej: "Electricidad marzo"), Categoría, Monto, Fecha, Comprobante adjunto (factura), Área responsable. Cada gasto se rastrea para presupuesto vs. real.',
        position: 'bottom',
        action: 'Registra 2-3 gastos de prueba',
        duration: 2,
      },
      {
        id: 'expenses-3',
        title: '📂 Categorías de Gasto',
        description: 'Servicios, Suministros, Mantenimiento, Publicidad, Viajes, Otros. Cada categoría se puede presupuestar y monitorear vs. límite. Análisis por categoría muestra dónde va más dinero.',
        position: 'top',
        action: 'Categoriza correctamente tus gastos',
      },
      {
        id: 'expenses-4',
        title: '📊 Análisis de Gastos',
        description: 'Reporte mensual/anual por categoría: Total gasto, % del total, varianza vs. presupuesto. Para contador: exporta para incluir en estados financieros, análisis de rentabilidad.',
        position: 'left',
        action: 'Genera reporte para decisiones',
      },
    ],
  },

  // ── Cheques ────────────────────────────────
  {
    moduleId: 'checks',
    moduleName: 'Gestión de Cheques',
    description: 'Administra cheques emitidos y recibidos',
    category: 'Operaciones',
    estimatedTime: 3,
    icon: 'Banknote',
    route: '/checks',
    steps: [
      {
        id: 'checks-1',
        title: '💰 Gestión de Cheques',
        description: 'Registro de cheques emitidos a proveedores y recibidos de clientes.',
        position: 'bottom',
        action: 'Observa los cheques',
      },
      {
        id: 'checks-2',
        target: '[data-tutorial="cheque-emitido"]',
        title: '📤 Cheques Emitidos',
        description: 'Cheques que emites para pagar a proveedores. Número, monto, fecha, banco.',
        position: 'bottom',
        action: 'Registra un cheque emitido',
        duration: 3,
      },
      {
        id: 'checks-3',
        target: '[data-tutorial="cheque-recibido"]',
        title: '📥 Cheques Recibidos',
        description: 'Cheques que recibes de clientes. Verifica números y endosos.',
        position: 'top',
        action: 'Registra un cheque recibido',
      },
      {
        id: 'checks-4',
        target: '[data-tutorial="cheque-status"]',
        title: '⏳ Estado del Cheque',
        description: 'Nuevo, Depositado, Presentado, Acreditado, Rechazado.',
        position: 'left',
        action: 'Actualiza el estado',
      },
    ],
  },

  // ── Promociones ────────────────────────────────
  {
    moduleId: 'promotions',
    moduleName: 'Promociones y Descuentos',
    description: 'Crea y gestiona promociones comerciales',
    category: 'Operaciones',
    estimatedTime: 3,
    icon: 'Tag',
    route: '/promotions',
    steps: [
      {
        id: 'promos-1',
        title: '🏷️ Promociones y Descuentos',
        description: 'Crea ofertas especiales para atraer clientes o limpiar stock antiguo.',
        position: 'bottom',
        action: 'Observa las promociones activas',
      },
      {
        id: 'promos-2',
        target: '[data-tutorial="new-promo"]',
        title: '➕ Crear Promoción',
        description: 'Nombre, productos incluidos, descuento, período de validez, límite de cantidad.',
        position: 'bottom',
        action: 'Inicia una nueva promoción',
        duration: 3,
      },
      {
        id: 'promos-3',
        target: '[data-tutorial="promo-rules"]',
        title: '📋 Reglas de la Promoción',
        description: 'Descuento por producto, por compra mínima, segunda unidad al 50%, etc.',
        position: 'top',
        action: 'Define las reglas',
      },
      {
        id: 'promos-4',
        target: '[data-tutorial="promo-performance"]',
        title: '📊 Desempeño de Promoción',
        description: 'Ventas generadas, productos vendidos, margen total de la promoción.',
        position: 'left',
        action: 'Analiza resultados',
      },
    ],
  },

  // ── Liquidaciones/Nómina ────────────────────────────────
  {
    moduleId: 'payroll',
    moduleName: 'Liquidaciones - Nómina',
    description: 'Gestiona salarios y nómina de empleados',
    category: 'RRHH',
    estimatedTime: 5,
    icon: 'Calculator',
    route: '/payroll',
    steps: [
      {
        id: 'payroll-1',
        title: '🧮 Sistema de Liquidaciones de Nómina',
        description: 'Cálculo automático de sueldos mensuales. Procesa: Sueldo básico, Horas extra (50%/100%), Bonificaciones, Descuentos (ausencias, deudas), Aportes (obra social 3%, sindicato), Impuesto Ganancias. Genera liquidación digital + papeles.',
        position: 'bottom',
        action: 'Observa nóminas/períodos procesados',
      },
      {
        id: 'payroll-2',
        title: '➕ Crear Liquidación Mensual',
        description: 'Botón Nueva. Selecciona: Mes/Año, Empleados a incluir, Verifica datos (sueldo, categoría, descuentos), Revisa cálculos automáticos, Confirma para generar nómina final. Sistema pre-valida aportes.',
        position: 'bottom',
        action: 'Crea liquidación de prueba',
        duration: 3,
      },
      {
        id: 'payroll-3',
        title: '💰 Componentes y Detalles',
        description: 'Cada liquidación muestra: Sueldo mensual, Horas extra trabajadas, Bonificaciones/incentivos, Deducciones (obra social, sindicato, segun impuesto Ganancias), Neto a pagar. Cada empleado ve su recibo.',
        position: 'top',
        action: 'Revisa componentes detalladamente',
        duration: 2,
      },
      {
        id: 'payroll-4',
        title: '📄 Generación de Documentos',
        description: 'Sistema genera automáticamente: (1) Recibo individual PDF para cada empleado (con firma digital), (2) Resumen para contabilidad, (3) Archivo para depósito bancario automático. Todo listo para contador/auditor.',
        position: 'left',
        action: 'Exporta nómina para pagar',
        duration: 2,
      },
    ],
  },

  // ── Comisiones ────────────────────────────────
  {
    moduleId: 'commissions',
    moduleName: 'Comisiones de Ventas',
    description: 'Calcula comisiones de vendedores',
    category: 'RRHH',
    estimatedTime: 4,
    icon: 'BadgePercent',
    route: '/commissions',
    steps: [
      {
        id: 'comm-1',
        title: '🎖️ Sistema Automático de Comisiones',
        description: 'Calcula automáticamente lo que debe recibir cada vendedor basado en sus ventas. Soporta: Comisión flat (% sobre total), Escala progresiva (más % si supera meta), Bonificación por volumen, Descuentos por devoluciones.',
        position: 'bottom',
        action: 'Observa tabla de comisiones del mes',
      },
      {
        id: 'comm-2',
        title: '📋 Configurar Reglas de Comisión',
        description: 'Define por vendedor/equipo: Porcentaje base (ej: 5%), Escala (ej: +1% si vende >$50k), Meta mensual, Bonificación especial. Sistema aplica automáticamente cada vez que vendedor realiza venta.',
        position: 'bottom',
        action: 'Revisa las reglas actuales',
        duration: 2,
      },
      {
        id: 'comm-3',
        title: '📊 Ventas y Comisión Calculada',
        description: 'Por cada vendedor: Total ventas del período, Comisión base, Bonificaciones (si aplican), Deducciones (si hay devoluciones), Total a pagar. Sistema rastrea en tiempo real.',
        position: 'top',
        action: 'Analiza comisiones por vendedor',
      },
      {
        id: 'comm-4',
        title: '✓ Validación e Incorporación a Nómina',
        description: 'Antes de pagar APRUEBA comisiones. Se incorporan automáticamente a liquidación de nómina. Vendedor ve detalle en su recibo de sueldo. Transparencia = más motivación.',
        position: 'left',
        action: 'Aprueba comisiones del mes',
      },
    ],
  },

  // ── Empleados ────────────────────────────────
  {
    moduleId: 'employees',
    moduleName: 'Gestión de Empleados',
    description: 'Administra tu equipo de trabajo',
    category: 'RRHH',
    estimatedTime: 4,
    icon: 'UserCircle',
    route: '/employees',
    steps: [
      {
        id: 'emp-1',
        title: '👤 Base de Datos de Empleados',
        description: 'Registro centralizado de tu equipo: Nombre, DNI, Fecha nacimiento, Domicilio, Contacto (teléfono/email), Cargo, Fecha ingreso, Salario base, Obra social afiliada, Beneficiario emergencia. Punto único de verdad para RRHH.',
        position: 'bottom',
        action: 'Observa lista de empleados',
      },
      {
        id: 'emp-2',
        title: '➕ Agregar Nuevo Empleado',
        description: 'Botón Nuevo. Completa: Datos personales (DNI importante para AFIP), Información de contacto, Domicilio legal, Cargo/Puesto, Salario acuerdo, Obra social, Beneficiario emergencia. Se valida DNI con AFIP automáticamente.',
        position: 'bottom',
        action: 'Agrega un empleado de prueba',
        duration: 3,
      },
      {
        id: 'emp-3',
        title: '📎 Documentación y Archivos',
        description: 'Sube documentos: Copia DNI, Acta de ingreso firmada, Contrato laboral, Certificado de obra social, Beneficiarios emergencia. Sistema los guarda en archivo digital. Imprescindible para auditoría laboral.',
        position: 'top',
        action: 'Adjunta documentos',
        duration: 2,
      },
      {
        id: 'emp-4',
        title: '🔒 Desactivación al Retirarse',
        description: 'Cuando empleado se retira: NO lo eliminas (pierde historial). Lo "Desactivas" (checkbox), así mantienes historial de ventas/comisiones/nóminas, pero no aparece en cálculos futuros. Audit trail perfecto para inspecciones.',
        position: 'left',
        action: 'Entiende ciclo de vida empleado',
      },
    ],
  },

  // ── Reportes ────────────────────────────────
  {
    moduleId: 'reports',
    moduleName: 'Reportes Generales',
    description: 'Análisis e informes de tu negocio',
    category: 'Reportes',
    estimatedTime: 5,
    icon: 'BarChart3',
    route: '/reports',
    steps: [
      {
        id: 'reports-1',
        title: '📊 Suite Completa de Reportes',
        description: 'Análisis multidimensional: Ventas (por producto, cliente, período), Inventario (rotación, caducidad, costos), Márgenes (bruto/neto por producto), Rentabilidad. Todos en tiempo real, exportables a Excel/PDF.',
        position: 'bottom',
        action: 'Explora reportes disponibles',
      },
      {
        id: 'reports-2',
        title: '💹 Reporte de Ventas Detallado',
        description: 'Total vendido, Productos top (ranking por volumen/valor), Clientes top (top 20 por gasto), Métodos de pago, Evolución diaria/semanal/mensual. Identificar oportunidades y tendencias.',
        position: 'bottom',
        action: 'Analiza tus ventas',
        duration: 3,
      },
      {
        id: 'reports-3',
        title: '📦 Reporte de Inventario',
        description: 'Stock actual vs. mínimo (qué reponer), Rotación (cuántas veces se vendió), Productos lentos (stock acumulado sin vender), Edad de inventario, Costo total en stock. Para optimizar capital de trabajo.',
        position: 'top',
        action: 'Monitorea inventario',
        duration: 2,
      },
      {
        id: 'reports-4',
        title: '💰 Análisis de Márgenes y Rentabilidad',
        description: 'Margen por producto (precio - costo), Margen bruto total, Rentabilidad neta, Comparativa vs. período anterior, Productos premium vs. commodities. Decisiones de pricing.',
        position: 'top',
        action: 'Optimiza precios',
        duration: 2,
      },
      {
        id: 'reports-5',
        title: '⬇️ Exportación y Compartición',
        description: 'Todos reportes exportables a: Excel (editable para análisis), PDF (para juntas/presentaciones). Comparte automáticamente con contador/junta directiva usando links seguros.',
        position: 'left',
        action: 'Exporta para análisis profundo',
        duration: 2,
      },
    ],
  },

  // ── Reportes de Contador ────────────────────────────────
  {
    moduleId: 'accountant_reports',
    moduleName: 'Reportes de Contador',
    description: 'Reportes fiscales y contables',
    category: 'Reportes',
    estimatedTime: 4,
    icon: 'BookOpen',
    route: '/accountant-reports',
    steps: [
      {
        id: 'acct-1',
        title: '📖 Reportes Contables',
        description: 'Informes para tu contador: balance, libro mayor, estado de resultados.',
        position: 'bottom',
        action: 'Observa reportes disponibles',
      },
      {
        id: 'acct-2',
        target: '[data-tutorial="balance-sheet"]',
        title: '📊 Estado de Resultados',
        description: 'Ingresos, gastos, utilidad generada en cada período.',
        position: 'bottom',
        action: 'Revisa resultados',
        duration: 3,
      },
      {
        id: 'acct-3',
        target: '[data-tutorial="book-movements"]',
        title: '📝 Libro Mayor',
        description: 'Todas las transacciones contables clasificadas por cuenta.',
        position: 'top',
        action: 'Consulta movimientos',
      },
      {
        id: 'acct-4',
        target: '[data-tutorial="tax-liability"]',
        title: '🧾 Obligaciones Fiscales',
        description: 'IVA, Ganancias, ByS y otros impuestos a pagar.',
        position: 'left',
        action: 'Verifica obligaciones',
      },
    ],
  },

  // ── Configuración de Email ────────────────────────────────
  {
    moduleId: 'settings_email',
    moduleName: 'Configuración de Email',
    description: 'Configura correos automáticos de tu negocio',
    category: 'Administración',
    estimatedTime: 3,
    icon: 'Settings',
    steps: [
      {
        id: 'email-1',
        title: '📧 Configuración de Email',
        description: 'Configura tu dominio de correo para enviar automáticamente desde la plataforma.',
        position: 'bottom',
        action: 'Observa la configuración',
      },
      {
        id: 'email-2',
        target: '[data-tutorial="email-server"]',
        title: '🖥️ Servidor SMTP',
        description: 'Host, puerto, usuario y contraseña de tu servidor de correo.',
        position: 'bottom',
        action: 'Configura servidor',
        duration: 3,
      },
      {
        id: 'email-3',
        target: '[data-tutorial="sender-address"]',
        title: '📤 Dirección de Envío',
        description: 'Email oficial desde el que se enviarán los correos automáticos.',
        position: 'top',
        action: 'Especifica correo',
      },
      {
        id: 'email-4',
        target: '[data-tutorial="test-email"]',
        title: '✉️ Envío de Prueba',
        description: 'Prueba la configuración enviando un correo de prueba.',
        position: 'left',
        action: 'Envía un correo de test',
      },
    ],
  },

  // ── Puntos de Venta AFIP ────────────────────────────────
  {
    moduleId: 'pos_afip',
    moduleName: 'Puntos de Venta AFIP',
    description: 'Administra tus puntos de venta fiscalizados',
    category: 'Administración',
    estimatedTime: 3,
    icon: 'Store',
    steps: [
      {
        id: 'posafip-1',
        title: '🏪 Puntos de Venta AFIP',
        description: 'Registro de tus puntos de venta fiscalizados ante la AFIP.',
        position: 'bottom',
        action: 'Observa tus PdV',
      },
      {
        id: 'posafip-2',
        target: '[data-tutorial="register-pdv"]',
        title: '➕ Registrar Punto de Venta',
        description: 'Nombre, número de caja, domicilio y tipo de comprobantes a utilizar.',
        position: 'bottom',
        action: 'Agrega un nuevo PdV',
        duration: 3,
      },
      {
        id: 'posafip-3',
        target: '[data-tutorial="voucher-types"]',
        title: '🧾 Tipos de Comprobantes',
        description: 'Facturas A, B, Tickets, Notas de Crédito, autorizadas en ese PdV.',
        position: 'top',
        action: 'Revisa comprobantes',
      },
      {
        id: 'posafip-4',
        target: '[data-tutorial="next-voucher"]',
        title: '📊 Próximo Comprobante',
        description: 'Número del próximo comprobante a emitir en cada punto de venta.',
        position: 'left',
        action: 'Verifica numeración',
      },
    ],
  },

  // ── Auditoría/Logs de Auditoría ────────────────────────────────
  {
    moduleId: 'audit_logs',
    moduleName: 'Auditoria/Logs',
    description: 'Registros de todas las acciones del sistema',
    category: 'Administración',
    estimatedTime: 3,
    icon: 'Shield',
    steps: [
      {
        id: 'audit-1',
        title: '🛡️ Logs de Auditoría',
        description: 'Registro detallado de todas las acciones: quién hizo qué, cuándo y dónde.',
        position: 'bottom',
        action: 'Observa los registros',
      },
      {
        id: 'audit-2',
        target: '[data-tutorial="filter-logs"]',
        title: '🔍 Filtrar Logs',
        description: 'Por usuario, acción (crear, editar, eliminar), módulo, fecha y resultado.',
        position: 'bottom',
        action: 'Aplica filtros',
        duration: 3,
      },
      {
        id: 'audit-3',
        target: '[data-tutorial="audit-detail"]',
        title: '📋 Detalle del Log',
        description: 'Usuario, acción, tabla afectada, valores antes/después, dirección IP.',
        position: 'top',
        action: 'Revisa un registro',
      },
      {
        id: 'audit-4',
        target: '[data-tutorial="export-audit"]',
        title: '📄 Exportar Auditoría',
        description: 'Descarga logs para análisis técnico o requerimientos de auditoría externa.',
        position: 'left',
        action: 'Exporta si lo necesitas',
      },
    ],
  },

  // ── Logs de Acceso ────────────────────────────────
  {
    moduleId: 'access_logs',
    moduleName: 'Logs de Acceso',
    description: 'Registro de accesos e intentos de login',
    category: 'Administración',
    estimatedTime: 3,
    icon: 'Activity',
    steps: [
      {
        id: 'access-1',
        title: '📊 Logs de Acceso',
        description: 'Registro de todos los logins, logouts e intentos fallidos de acceso.',
        position: 'bottom',
        action: 'Observa accesos',
      },
      {
        id: 'access-2',
        target: '[data-tutorial="login-history"]',
        title: '📝 Historial de Login',
        description: 'Quién se conectó, cuándo, desde qué IP, si fue exitoso.',
        position: 'bottom',
        action: 'Revisa conexiones',
        duration: 3,
      },
      {
        id: 'access-3',
        target: '[data-tutorial="failed-attempts"]',
        title: '⚠️ Intentos Fallidos',
        description: 'Múltiples intentos fallidos pueden indicar intento de acceso no autorizado.',
        position: 'top',
        action: 'Identifica anomalías',
      },
      {
        id: 'access-4',
        target: '[data-tutorial="security-alert"]',
        title: '🔒 Alertas de Seguridad',
        description: 'Se puede investigar actividad sospechosa y cambiar contraseña si es necesario.',
        position: 'left',
        action: 'Monitorea seguridad',
      },
    ],
  },

  // ── Monitoreo de Inventario ────────────────────────────────
  {
    moduleId: 'inventory_alerts',
    moduleName: 'Alertas de Inventario',
    description: 'Monitorea productos con bajo stock',
    category: 'Inventario',
    estimatedTime: 3,
    icon: 'AlertCircle',
    steps: [
      {
        id: 'invalerts-1',
        title: '⚠️ Alertas de Inventario',
        description: 'Productos que han caído por debajo del stock mínimo configurado.',
        position: 'bottom',
        action: 'Observa las alertas',
      },
      {
        id: 'invalerts-2',
        target: '[data-tutorial="low-stock"]',
        title: '📉 Stock Bajo',
        description: 'Productos casi agotados que necesitan reposición urgente.',
        position: 'bottom',
        action: 'Prioriza reposición',
        duration: 3,
      },
      {
        id: 'invalerts-3',
        target: '[data-tutorial="critical-stock"]',
        title: '🚨 Stock Crítico',
        description: 'Productos a punto de agotarse. Pueden no poderse vender si no repones ya!',
        position: 'top',
        action: 'Actúa de inmediato',
      },
      {
        id: 'invalerts-4',
        target: '[data-tutorial="create-po-alert"]',
        title: '📦 Crear PO automática',
        description: 'Crea una orden de compra directamente desde la alerta.',
        position: 'left',
        action: 'Ordena reposición',
      },
    ],
  },

  // ── Almacenes/Depósitos ────────────────────────────────
  {
    moduleId: 'warehouses',
    moduleName: 'Gestión de Almacenes',
    description: 'Administra múltiples depósitos y ubicaciones',
    category: 'Inventario',
    estimatedTime: 3,
    icon: 'Warehouse',
    steps: [
      {
        id: 'whse-1',
        title: '🏢 Gestión de Almacenes',
        description: 'Si tienes múltiples depósitos, administra inventario independiente en cada uno.',
        position: 'bottom',
        action: 'Observa tus almacenes',
      },
      {
        id: 'whse-2',
        target: '[data-tutorial="create-warehouse"]',
        title: '➕ Crear Almacén',
        description: 'Nombre del depósito, ubicación, responsable, capacidad.',
        position: 'bottom',
        action: 'Agrega un almacén',
        duration: 3,
      },
      {
        id: 'whse-3',
        target: '[data-tutorial="warehouse-stock"]',
        title: '📊 Stock por Almacén',
        description: 'Cada depósito tiene su propio inventario independiente.',
        position: 'top',
        action: 'Revisa stocks',
      },
      {
        id: 'whse-4',
        target: '[data-tutorial="warehouse-manager"]',
        title: '👤 Responsable de Almacén',
        description: 'Asigna un empleado responsable para cada depósito.',
        position: 'left',
        action: 'Define responsables',
      },
    ],
  },

  // ── Stock por Depósito ────────────────────────────────
  {
    moduleId: 'warehouse_stock',
    moduleName: 'Stock por Depósito',
    description: 'Consulta stock específico en cada almacén',
    category: 'Inventario',
    estimatedTime: 3,
    icon: 'PackageSearch',
    steps: [
      {
        id: 'whstock-1',
        title: '🔍 Consulta de Stock por Depósito',
        description: 'Dónde hay más stock de cada producto en tus diferentes almacenes.',
        position: 'bottom',
        action: 'Busca un producto',
      },
      {
        id: 'whstock-2',
        target: '[data-tutorial="warehouse-select"]',
        title: '📍 Seleccionar Depósito',
        description: 'Filtra por depósito para ver solo el stock de ese lugar.',
        position: 'bottom',
        action: 'Selecciona un almacén',
        duration: 3,
      },
      {
        id: 'whstock-3',
        target: '[data-tutorial="available-stock"]',
        title: '📦 Stock Disponible',
        description: 'Stock actual, reservado, disponible para vender en ese depósito.',
        position: 'top',
        action: 'Verifica disponibilidad',
      },
      {
        id: 'whstock-4',
        target: '[data-tutorial="transfer-between"]',
        title: '↔️ Transferir Stock',
        description: 'Si un producto falta en un depósito, transfierelo desde otro.',
        position: 'left',
        action: 'Realiza una transferencia',
      },
    ],
  },

  // ── Transferencias entre Depósitos ────────────────────────────────
  {
    moduleId: 'warehouse_transfers',
    moduleName: 'Transferencias entre Depósitos',
    description: 'Mueve inventario entre almacenes',
    category: 'Inventario',
    estimatedTime: 3,
    icon: 'ArrowLeftRight',
    steps: [
      {
        id: 'transfer-1',
        title: '↔️ Transferencias de Stock',
        description: 'Mueve productos de un depósito a otro cuando sea necesario.',
        position: 'bottom',
        action: 'Observa las transferencias',
      },
      {
        id: 'transfer-2',
        target: '[data-tutorial="new-transfer"]',
        title: '➕ Crear Transferencia',
        description: 'Depósito origen, depósito destino, productos y cantidades.',
        position: 'bottom',
        action: 'Inicia una transferencia',
        duration: 3,
      },
      {
        id: 'transfer-3',
        target: '[data-tutorial="transfer-products"]',
        title: '📦 Seleccionar Productos',
        description: 'Elige qué productos transferir y en qué cantidad.',
        position: 'top',
        action: 'Selecciona productos',
      },
      {
        id: 'transfer-4',
        target: '[data-tutorial="confirm-transfer"]',
        title: '✅ Confirmar Transferencia',
        description: 'El depósito origen pierde el stock, el destino lo recibe.',
        position: 'left',
        action: 'Confirma la transferencia',
      },
    ],
  },

  // ── Reservas de Stock ────────────────────────────────
  {
    moduleId: 'stock_reservations',
    moduleName: 'Reservas de Stock',
    description: 'Gestiona stock reservado para órdenes',
    category: 'Inventario',
    estimatedTime: 3,
    icon: 'PackageOpen',
    steps: [
      {
        id: 'sres-1',
        title: '📦 Reservas de Stock',
        description: 'Cuando se crea orden no confirmada, el stock se reserva (no se vende a otro).',
        position: 'bottom',
        action: 'Observa reservas',
      },
      {
        id: 'sres-2',
        target: '[data-tutorial="reserved-items"]',
        title: '⏳ Items Reservados',
        description: 'Productos reservados en órdenes pendientes de confirmación o pago.',
        position: 'bottom',
        action: 'Revisa reservas',
        duration: 3,
      },
      {
        id: 'sres-3',
        target: '[data-tutorial="release-reservation"]',
        title: '🔓 Liberar Reserva',
        description: 'Si una orden se cancela, libera el stock para que esté disponible nuevamente.',
        position: 'top',
        action: 'Libera si es necesario',
      },
      {
        id: 'sres-4',
        target: '[data-tutorial="confirm-sale"]',
        title: '✅ Confirmar Venta',
        description: 'Cuando se confirma venta, la reserva se convierte en venta real.',
        position: 'left',
        action: 'Confirma ventas',
      },
    ],
  },

  // ── Cierre Mensual ────────────────────────────────
  {
    moduleId: 'monthly_closing',
    moduleName: 'Cierre Mensual',
    description: 'Cierre contable y operativo del mes',
    category: 'Administración',
    estimatedTime: 5,
    icon: 'Lock',
    steps: [
      {
        id: 'close-1',
        title: '🔒 Cierre Mensual',
        description: 'Proceso de cierre: verificar datos, generar reportes finales y bloquear período.',
        position: 'bottom',
        action: 'Comienza el proceso',
      },
      {
        id: 'close-2',
        target: '[data-tutorial="verify-data"]',
        title: '✔️ Verificar Datos',
        description: 'Revisa que todas las transacciones del mes estén registradas correctamente.',
        position: 'bottom',
        action: 'Valida información',
        duration: 3,
      },
      {
        id: 'close-3',
        target: '[data-tutorial="closing-checklist"]',
        title: '📋 Checklist de Cierre',
        description: 'Lista de verificación: reconciliación bancaria, inventario físico, saldos.',
        position: 'top',
        action: 'Completa checklist',
      },
      {
        id: 'close-4',
        target: '[data-tutorial="generate-reports"]',
        title: '📊 Generar Reportes',
        description: 'Crea reportes finales del mes para análisis y archivos.',
        position: 'top',
        action: 'Genera reportes',
      },
      {
        id: 'close-5',
        target: '[data-tutorial="lock-period"]',
        title: '🔐 Bloquear Período',
        description: 'Una vez cerrado, no se pueden hacer cambios en transacciones del mes.',
        position: 'left',
        action: 'Cierra el período',
      },
    ],
  },

  // ── Operaciones Masivas ────────────────────────────────
  {
    moduleId: 'bulk_operations',
    moduleName: 'Operaciones Masivas',
    description: 'Realiza cambios en lote de múltiples registros',
    category: 'Administración',
    estimatedTime: 4,
    icon: 'Zap',
    steps: [
      {
        id: 'bulk-1',
        title: '⚡ Operaciones Masivas',
        description: 'Realiza cambios rapidamente en múltiples registros a la vez.',
        position: 'bottom',
        action: 'Observa opciones disponibles',
      },
      {
        id: 'bulk-2',
        target: '[data-tutorial="bulk-price-update"]',
        title: '💰 Actualizar Precios',
        description: 'Sube todos los precios un porcentaje, aplica descuento masivo, etc.',
        position: 'bottom',
        action: 'Selecciona productos',
        duration: 3,
      },
      {
        id: 'bulk-3',
        target: '[data-tutorial="bulk-stock-update"]',
        title: '📦 Actualizar Stock',
        description: 'Ajusta inventario de múltiples productos con una operación.',
        position: 'top',
        action: 'Actualiza stock',
      },
      {
        id: 'bulk-4',
        target: '[data-tutorial="preview"]',
        title: '👁️ Previsualizar Cambios',
        description: 'Antes de confirmar, revisa qué cambios se aplicarán.',
        position: 'left',
        action: 'Verifica cambios',
      },
    ],
  },

  // ── Configuración de Notificaciones ────────────────────────────────
  {
    moduleId: 'notifications',
    moduleName: 'Configuración de Notificaciones',
    description: 'Personaliza alertas y notificaciones del sistema',
    category: 'Administración',
    estimatedTime: 3,
    icon: 'Bell',
    steps: [
      {
        id: 'notif-1',
        title: '🔔 Configuración de Notificaciones',
        description: 'Controla qué alertas recibes, cuándo y por qué canales.',
        position: 'bottom',
        action: 'Observa opciones',
      },
      {
        id: 'notif-2',
        target: '[data-tutorial="notification-types"]',
        title: '📢 Tipos de Notificación',
        description: 'Alertas de stock bajo, nuevas órdenes, pagos recibidos, recordatorios, etc.',
        position: 'bottom',
        action: 'Activa/desactiva alertas',
        duration: 3,
      },
      {
        id: 'notif-3',
        target: '[data-tutorial="notification-channels"]',
        title: '📧 Canales de Entrega',
        description: 'En app, email, SMS, notificaciones del navegador.',
        position: 'top',
        action: 'Elige canales',
      },
      {
        id: 'notif-4',
        target: '[data-tutorial="notification-frequency"]',
        title: '⏰ Frecuencia',
        description: 'Al instante, resumen diario, semanal. Como prefieras.',
        position: 'left',
        action: 'Configura frecuencia',
      },
    ],
  },

  // ── Integraciones ────────────────────────────────
  {
    moduleId: 'integrations',
    moduleName: 'Integraciones',
    description: 'Conecta con otras plataformas y servicios',
    category: 'Administración',
    estimatedTime: 4,
    icon: 'Plug',
    steps: [
      {
        id: 'integ-1',
        title: '🔌 Integraciones',
        description: 'Conecta tu sistema con otras plataformas: contabilidad, e-commerce, marketplaces.',
        position: 'bottom',
        action: 'Observa integraciones',
      },
      {
        id: 'integ-2',
        target: '[data-tutorial="available-integrations"]',
        title: '⚙️ Integraciones Disponibles',
        description: 'Sistema contable, tienda online, marketplaces (MercadoLibre, etc).',
        position: 'bottom',
        action: 'Explora opciones',
        duration: 3,
      },
      {
        id: 'integ-3',
        target: '[data-tutorial="connect-integration"]',
        title: '🔗 Conectar Integración',
        description: 'Sigue pasos para autorizar y conectar cada plataforma.',
        position: 'top',
        action: 'Conecta una plataforma',
      },
      {
        id: 'integ-4',
        target: '[data-tutorial="integration-sync"]',
        title: '🔄 Sincronización',
        description: 'Datos se sincronizan automáticamente entre plataformas.',
        position: 'left',
        action: 'Verifica sincronización',
      },
    ],
  },

  // ── Facturación AFIP ────────────────────────────────
  {
    moduleId: 'afip',
    moduleName: 'Facturación AFIP',
    description: 'Generación de facturas fiscalizadas por AFIP',
    category: 'Administración',
    estimatedTime: 4,
    icon: 'Store',
    steps: [
      {
        id: 'afip-1',
        title: '🏪 Facturación AFIP',
        description: 'Generación de facturas electrónicas fiscalizadas ante la AFIP.',
        position: 'bottom',
        action: 'Observa configuración',
      },
      {
        id: 'afip-2',
        target: '[data-tutorial="afip-status"]',
        title: '📊 Estado de Facturación',
        description: 'Verifica que tu empresa esté registrada y autorizada en AFIP.',
        position: 'bottom',
        action: 'Confirma autorización',
        duration: 3,
      },
      {
        id: 'afip-3',
        target: '[data-tutorial="invoice-types"]',
        title: '🧾 Tipos de Comprobantes',
        description: 'Facturas A, B, Notas de Crédito/Débito autorizadas por AFIP.',
        position: 'top',
        action: 'Configura tipos',
      },
      {
        id: 'afip-4',
        target: '[data-tutorial="invoice-number"]',
        title: '#️⃣ Numeración',
        description: 'Rango de números de factura autorizado por AFIP.',
        position: 'left',
        action: 'Verifica numeración',
      },
    ],
  },

  // ── Configuración General ────────────────────────────────
  {
    moduleId: 'settings',
    moduleName: 'Configuración General',
    description: 'Personaliza tu cuenta y preferencias',
    category: 'Administración',
    estimatedTime: 3,
    icon: 'Settings',
    steps: [
      {
        id: 'settings-1',
        title: '⚙️ Configuración General',
        description: 'Aquí configuras datos de tu empresa, logo, nombre y datos fiscales.',
        position: 'bottom',
        action: 'Observa las opciones disponibles',
      },
      {
        id: 'settings-2',
        target: '[data-tutorial="company-info"]',
        title: '🏢 Datos de la Empresa',
        description: 'Nombre, CUIT, razón social y datos de contacto que aparecen en facturas y documentos.',
        position: 'bottom',
        action: 'Actualiza si es necesario',
        duration: 3,
      },
      {
        id: 'settings-3',
        target: '[data-tutorial="payment-methods"]',
        title: '💳 Métodos de Pago',
        description: 'Aquí habilitas los métodos de pago que aceptas: efectivo, tarjeta, transferencia, etc.',
        position: 'top',
        action: 'Haz clic para ver y configurar métodos',
      },
    ],
  },

  // ── Migración de Datos (ESPECIAL) ────────────────────────────────
  {
    moduleId: 'migration',
    moduleName: 'Guía de Migración Completa',
    description: 'Migra tus datos desde tu sistema anterior a GEROS en 7 pasos',
    category: 'Inicio',
    estimatedTime: 30,
    icon: 'Upload',
    route: '/app',
    steps: [
      {
        id: 'migration-1',
        title: '🚀 Bienvenida a GEROS - Tu Nueva Plataforma de Gestión',
        description: 'Vas a migrar TODOS tus datos desde tu sistema anterior: Clientes, Productos, Ventas históricas, Proveedores, Empleados, Cuentas bancarias. El proceso es seguro, rápido y con validaciones que evitan perder información. Tiempo total: ~1-2 horas para empresa mediana.',
        position: 'bottom',
        action: 'Continúa leyendo esta guía paso a paso',
        duration: 2,
        route: '/app',
      },
      {
        id: 'migration-2',
        title: '📋 PASO 1: Exporta datos de tu sistema anterior',
        description: 'En tu sistema actual accede a: Configuración → Exportar Datos. Descarga estos archivos en Excel/CSV: Clientes (nombre, teléfono, dirección, límite crédito), Productos (código, nombre, precio, stock), Proveedores, Empleados, Movimientos bancarios últimos 12 meses. Nos da datos limpios para importar.',
        position: 'bottom',
        action: 'Ten los Excel listos en tu escritorio',
        duration: 3,
      },
      {
        id: 'migration-3',
        title: '🏢 PASO 2: Configura Datos Básicos de Empresa',
        description: 'En GEROS → Configuración → Datos de Empresa. Completa: Nombre (debe coincidir con CUIT), CUIT/DNI, Razón social, Email principal para notificaciones, Logo/Imagotipo. Estos datos aparecerán en TODAS las facturas/documentos, así que verifica muy bien.',
        position: 'bottom',
        action: 'Abre Configuración General',
        duration: 3,
        route: '/settings/general',
      },
      {
        id: 'migration-4',
        title: '💳 PASO 3: Configura Métodos de Pago y Cuentas Bancarias',
        description: 'GEROS → Configuración → Métodos de Pago. Habilita: Efectivo (sin recargo), Débito (sin recargo), Crédito (elige cuotas soportadas: 1/3/6/12 con sus recargos %), Cheque, Transferencia. → GEROS → Finanzas → Cuentas Bancarias. Agrega TODAS tus cuentas (corriente, caja ahorro, etc) con saldo inicial al 1 de hoy.',
        position: 'bottom',
        action: 'Configura antes de importar ventas',
        duration: 4,
        route: '/settings/payment-methods',
      },
      {
        id: 'migration-5',
        title: '👥 PASO 4: Importa tu Base de Clientes',
        description: 'GEROS → Clientes → Importar (botón arriba). Carga Excel con clientes. Sistema valida: CUIT único (no duplicados), Email formato correcto, Teléfono. Si hay errores, descarga reporte, corrigue en Excel, reintentas. Una vez importado: 20 clientes = OK, verifica 2-3 perfiles para datos correctos.',
        position: 'bottom',
        action: 'Importa archivo Clientes.xlsx',
        duration: 5,
        route: '/customers',
      },
      {
        id: 'migration-6',
        title: '📦 PASO 5: Importa Catálogo de Productos',
        description: 'GEROS → Productos → Importar. Carga Excel con: SKU (código único), Nombre, Precio costo, Precio venta (sistema calcula margen automáticamente), Stock inicial (saldo al hoy), Categoría, Código barras (opcional). Sistema valida: SKU único, precios numéricos, códigos válidos. Verifica: Stock total coincide vs. inventario físico real.',
        position: 'bottom',
        action: 'Importa archivo Productos.xlsx',
        duration: 5,
        route: '/products',
      },
      {
        id: 'migration-7',
        title: '🏭 PASO 6: Importa Proveedores y Empleados',
        description: 'GEROS → Compras → Proveedores → Importar. Carga con: Nombre, CUIT, Contacto, Teléfono, Email, Condiciones de pago (plazo). → GEROS → RRHH → Empleados → Importar. Carga con: Nombre, DNI, Puesto, Salario, Obra social, Beneficiario emergencia. Verifica en ambos casos que los datos se vean correctos.',
        position: 'bottom',
        action: 'Importa Proveedores.xlsx + Empleados.xlsx',
        duration: 5,
        route: '/suppliers',
      },
      {
        id: 'migration-8',
        title: '💰 PASO 7: Cierra Saldos Iniciales',
        description: 'GEROS → Finanzas → Movimientos Bancarios. Registra saldo inicial en cada cuenta al 1 de hoy. GEROS → Clientes → Cuentas Corrientes. Registra saldos pendientes de clientes (deudas previas). GEROS → Compras → (verifica compras pendientes). Sistema ahora tiene TODOS tus datos históricos= base de datos limpia, lista para operaciones diarias.',
        position: 'bottom',
        action: 'Completa registro de saldos iniciales',
        duration: 4,
        route: '/finances',
      },
      {
        id: 'migration-9',
        title: '✅ VALIDACIÓN FINAL: Reconcilia Datos',
        description: 'GEROS → Dashboard. Revisa: Total clientes importados (debe ser X), Total productos activos (debe ser Y), Stock total valorizado (debe ser Z). GEROS → Reportes → Inventario. Descargar, comparar vs. Excel original para asegurar nada se perdió. Si todo cuadra = ¡Migración exitosa!',
        position: 'bottom',
        action: 'Valida números vs. sistema anterior',
        duration: 3,
        route: '/app',
      },
      {
        id: 'migration-10',
        title: '🎓 PRÓXIMOS PASOS: Capacitación de Equipo',
        description: 'Ahora que tienes datos, entrena a tu equipo: (1) Vendedores → Módulo POS (vender rápido), (2) Jefe de almacén → Inventario (reposición, stock), (3) Contador → Reportes + Finanzas (números diarios). Cada rol tiene su tutorial dedicado en Centro de Aprendizaje.',
        position: 'bottom',
        action: 'Ve al Centro de Aprendizaje para más tutoriales',
        duration: 2,
        route: '/learning',
      },
    ],
  },

  // ── Centro de Aprendizaje ────────────────────────────────
  {
    moduleId: 'learning_center',
    moduleName: 'Centro de Aprendizaje',
    description: 'Tu plataforma de tutoriales interactivos',
    category: 'Recursos',
    estimatedTime: 3,
    icon: 'BookOpen',
    steps: [
      {
        id: 'learning-1',
        title: '📖 Bienvenido al Centro de Aprendizaje',
        description: 'Este es tu Hub central de tutoriales. Aquí encontrarás GUÍAS INTERACTIVAS para cada módulo: Cada tutorial explica qué hace el módulo, cómo usarlo, y sirve como capacitación para tu equipo. Todos nuestros 40+ tutoriales están organizados por categoría.',
        position: 'bottom',
        action: 'Observa la estructura de tutoriales',
      },
      {
        id: 'learning-2',
        title: '📚 Tutoriales Organizados por Categoría',
        description: 'Verás: (1) Inicio (Dashboard, Migración), (2) Ventas (POS, Facturas, Presupuestos), (3) Clientes (Base de datos, Cuentas corrientes), (4) Compras (Proveedores, Órdenes), (5) Finanzas (Bancos, Tesorería), (6) RRHH (Empleados, Nómina), (7) Reportes, (8) Administración. Cada una agrupa módulos relacionados para flujo natural de aprendizaje.',
        position: 'bottom',
        action: 'Explora cada categoría',
        duration: 2,
      },
      {
        id: 'learning-3',
        title: '▶️ Cómo Ejecutar un Tutorial',
        description: 'Cada tutorial tiene botón "Comenzar Tutorial" (verde). Al clickearlo: Interfaz oscurece, un panel te guía paso a paso, resalta elementos importantes, explica qué hacer. Puedes pausar en cualquier momento. Perfecto para: aprender nuevas funciones, entrenar nuevos empleados, recordar procesos olvidados.',
        position: 'bottom',
        action: 'Elige un tutorial y comienza',
        duration: 2,
      },
      {
        id: 'learning-4',
        title: '⏱️ Tiempo de Cada Tutorial = 3-30 minutos',
        description: 'Tutoriales cortos (3-4 min): Explicación rápida de función simple (ej: Dashboard). Tutoriales medios (10-15 min): Procesos completos (ej: Crear venta POS). Tutoriales largos (30 min): Procesos complejos (ej: Migración de datos). Cada uno indica tiempo estimado antes de comenzar.',
        position: 'bottom',
        action: 'Planifica tiempo según duración',
        duration: 2,
      },
      {
        id: 'learning-5',
        title: '👥 Comparte Tutoriales con tu Equipo',
        description: 'Puedes copiar link de cualquier tutorial y enviarlo por WhatsApp/Email a tu equipo. Vendedor nuevo abre link, automáticamente entra en tutorial interactivo sin necesidad que le enseñes personalmente. Ahorra tiempo de capacitación: envía link → estudian → preguntan dudas específicas.',
        position: 'bottom',
        action: 'Copia link de un tutorial para compartir',
      },
    ],
  },

  // ── Base de Conocimiento ────────────────────────────────
  {
    moduleId: 'knowledge_base',
    moduleName: 'Base de Conocimiento',
    description: 'Respuestas a preguntas frecuentes y solución de problemas',
    category: 'Recursos',
    estimatedTime: 4,
    icon: 'BookOpen',
    steps: [
      {
        id: 'kb-1',
        title: '🔍 Base de Conocimiento - Preguntas Frecuentes',
        description: 'Artículos escritos (no interactivos) sobre: Procesos (cómo facturar, cómo registrar pago), Problemas frecuentes (por qué me da error, cómo recupero datos), Mejores prácticas (qué precio poner, cómo categorizar gastos). Cada artículo tiene título claro, pasos numerados, imágenes si aplica.',
        position: 'bottom',
        action: 'Busca un tema que te interese',
      },
      {
        id: 'kb-2',
        title: '🔎 Busca por Palabra Clave',
        description: 'Campo de búsqueda arriba. Escribe palabra (ej: "devolución", "descuento", "stock") y sistema filtra artículos relevantes. Muy útil si tienes duda específica y no quieres leer tutorial completo.',
        position: 'bottom',
        action: 'Prueba buscar un tema',
        duration: 2,
      },
      {
        id: 'kb-3',
        title: '📂 Navega por Categorías',
        description: 'Sidebar izquierdo agrupa artículos: Vendedores (POS, facturas), Almacén (stock, reposición), Contador (reportes, impuestos), Admin (configuración, usuarios). Abre categoría y ves todos artículos disponibles de ese tema.',
        position: 'bottom',
        action: 'Abre 2-3 categorías',
      },
      {
        id: 'kb-4',
        title: '⭐ Artículos Recomendados según tu Rol',
        description: 'Sistema aprende tu rol (vendedor, gerente, contador) y te sugiere artículos relevantes cada vez que entras. Vendedor? Te muestra "Cómo cambiar precio en POS". Contador? Te muestra "Cómo conciliar bancos". Ahorro de tiempo buscando.',
        position: 'bottom',
        action: 'Observa artículos sugeridos',
      },
    ],
  },

  // ── Soporte de Plataforma ────────────────────────────────
  {
    moduleId: 'platform_support',
    moduleName: 'Soporte de Plataforma GEROS',
    description: 'Contacta con equipo técnico de soporte',
    category: 'Recursos',
    estimatedTime: 2,
    icon: 'LifeBuoy',
    steps: [
      {
        id: 'support-1',
        title: '🆘 Centro de Soporte Técnico',
        description: 'Si tienes problema técnico (error en pantalla, función que no funciona, datos perdidos) o pregunta que no puedes resolver solo. Aquí contactas al equipo GEROS: Vía chat en vivo (respuesta en minutos si está online), Email, Teléfono. Cada ticket se asigna a especialista que da seguimiento.',
        position: 'bottom',
        action: 'Explora canales de contacto',
      },
      {
        id: 'support-2',
        title: '💬 Chat en Vivo - Soporte Inmediato',
        description: 'Botón inferior derecha en cualquier página GEROS. Abre ventana chat. Escribes consulta, especialista responde en segundos/minutos. Perfecto para: dudas rápidas, problemas urgentes, pasos que no entiendes. Horario: Lunes-Viernes 9am-6pm.',
        position: 'bottom',
        action: 'Abre chat si necesitas ayuda inmediata',
        duration: 2,
      },
      {
        id: 'support-3',
        title: '📧 Email y Tickets',
        description: 'Para consultas complejas que requieren análisis profundo: datos a revisar, problema que reproduce paso a paso. Envías email → sistema abre TICKET automático → especialista responde en 24 horas. Tienes número ticket para dar seguimiento.',
        position: 'bottom',
        action: 'Usa email para consultas complejas',
      },
    ],
  },
];

// Utility function to get a tutorial by module ID
export function getTutorialByModuleId(moduleId: string): ModuleTutorial | undefined {
  return TUTORIAL_MODULES.find(module => module.moduleId === moduleId);
}
